opensearch-project/opensearch-ci

README.md
Signed-off-by: Peter Nied <petern@amazon.com>
=> Remove the global install requirement

.github/workflows/cdk.yml
Signed-off-by: Peter Nied <petern@amazon.com>
Resolves: https://github.com/opensearch-project/opensearch-ci/issues/12
=> Add workflow for CDK Build and Test

.github/workflows/dco.yml
Adding the DCO check to this repository, have a virtually identical change https://github.com/opensearch-project/.github/pull/45 for the organization
- https://github.com/opensearch-project/opensearch-build/issues/619
=> Developer Certificate of Origin workflow

README.md
Add bootstrap documentation. Format numerical bullet points (click on `view file` to see the changes). 
=> Add bootstrap documentation

lib/ci-stack.ts
Add CIStackProps for setting parameters programmatically.  This is useful for calling this CDK library programmatically.
Note; did the string template modification to make this a smaller change
=> Add CIStackProps for setting parameters programmatically

lib/compute/jenkins-main-node.ts
Signed-off-by: Peter Nied <petern@amazon.com>
See the new cloudformation output:
Before:
```
"029": {
"command": "java -jar /jenkins-cli.jar -s http://localhost:8080 -auth @/var/lib/jenkins/secrets/myIdPassDefault install-plugin token-macro trilead-api uno-choice validating-string-parameter variant windows-slaves workflow-aggregator workflow-api workflow-basic-steps workflow-cps "
},
"030": {
"command": "java -jar /jenkins-cli.jar -s http://localhost:8080 -auth @/var/lib/jenkins/secrets/myIdPassDefault install-plugin workflow-cps-global-lib workflow-durable-task-step workflow-job workflow-multibranch workflow-scm-step workflow-step-api workflow-support ws-cleanup xml-job-to-job-dsl java -jar /jenkins-cli.jar -s http://localhost:8080 -auth @/var/lib/jenkins/secrets/myIdPassDefault restart" …
```
=> Add missing && operator when restarting jenkins after plugin install

lib/compute/jenkins-main-node.ts, test/compute/jenkins-main-node.test.ts
The previous change didn't work and while we were troubleshooting manually, replicating the same steps as automation it worked. Trying this way now.
=> Reload config after enabling RBAC

lib/compute/jenkins-plugins.ts
=> Add pipeline aws

lib/compute/jenkins-main-node.ts
As per my research, configuration as code plugin automatically loads configuration if jenkins.yaml is found in jenkins_home directory. Due to this, before we can make any changes to the yaml and reload the configuration, the old config is already loaded by jenkins.
This PR changes yaml filename for initial config, makes necessary changes to the file and then saves it as jenkins.yaml and loads via reload command. This will also help us debug the initial config posted via code and the changes made to the yaml in the EC2.
For more information on following Developer Certificate of Origin …
=> Fix loading yaml for jcasc

lib/compute/oidc-config.ts
=> Add missing OIDC values

lib/compute/agent-nodes.ts
Raise the gradle check runner to have c518xlarge as in Fork Jenkins
https://github.com/opensearch-project/opensearch-build/issues/851
=> Raise the gradle check runner to have c518xlarge as in Fork Jenkins

lib/compute/agent-node-config.ts, lib/compute/agent-nodes.ts
Make sure gradle check agent only runs once
https://github.com/opensearch-project/opensearch-build/issues/2324
=> Make sure gradle check agent only runs once

lib/compute/agent-node-config.ts, lib/compute/agent-nodes.ts
Make agent label have consistent capital naming (opensearch-ci)
Corresponding opensearch-ci PR: https://github.com/opensearch-project/opensearch-build/pull/2353
https://github.com/opensearch-project/opensearch-ci/issues/132
=> Make agent label have consistent capital naming (opensearch-ci)

lib/compute/agent-node-config.ts, lib/compute/agent-nodes.ts
Add macos version to the label
#122
=> Add macos version to the label

lib/compute/agent-nodes.ts
Recently there are issues with yum db updates after cleaning up caches:
```
Transaction test succeeded
Running transaction
Traceback (most recent call last):
File "/bin/yum", line 29, in <module>
yummain.user_main(sys.argv[1:], exit_code=True)
File "/usr/share/yum-cli/yummain.py", line 375, in user_main
errcode = main(args)
File "/usr/share/yum-cli/yummain.py", line 281, in main
return_code = base.doTransaction()
File "/usr/share/yum-cli/cli.py", line 816, in doTransaction
resultobject = self.runTransaction(cb=cb)
File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1833, in runTransaction
lastdbv = self.history.last()
File "/usr/lib/python2.7/site-packages/yum/history.py", line 1271, in last
ret = self.old([], 1, …
```
=> Add yum db cleanup to AL2 and remove lock to Ubuntu2004

packer/config/windows/launch-config.json, packer/jenkins-agent-win2016-x64.json, packer/jenkins-agent-win2019-x64-alpine-wsl.json, packer/jenkins-agent-win2019-x64.json
Remove fixed password setups in Windows Packer
=> Remove fixed password setups in Windows Packer

README.md, lib/ci-stack.ts, lib/compute/agent-node-config.ts, lib/compute/agent-nodes.ts, lib/compute/jenkins-main-node.ts, lib/security/ci-security-groups.ts, packer/README.md, packer/jenkins-agent-win2016-x64.json, packer/jenkins-agent-win2019-x64-alpine-wsl.json, packer/jenkins-agent-win2019-x64.json, packer/scripts/windows/userdata.ps1
Adding new Windows agent and organize Mac agent configurations
=> Adding new Windows agent and organize Mac agent configurations

lib/compute/agent-node-config.ts, lib/compute/agent-nodes.ts
Update agent setups so each executor takes 4 cores
Part of opensearch-project/opensearch-build#2271
=> Update agent setups so each executor takes 4 cores

lib/compute/agent-nodes.ts
Fix Ubuntu agent start up on userdata
https://github.com/opensearch-project/opensearch-ci/issues/188
=> Fix Ubuntu agent start up on userdata

lib/compute/agent-nodes.ts, packer/README.md, packer/scripts/al2/al2-agent-setups.sh, packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
Resolve agent connect to docker socket issues.
The issue is due to the user ec2-user for AL2 and ubuntu for Ubuntu2004 not added to the docker group, thus have no access to the docker socket.
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied
```
https://github.com/opensearch-project/opensearch-ci/issues/188
For more information on following Developer Certificate of Origin and signing off your commits, please check …
=> Resolve agent connect to docker socket issues

lib/compute/agent-nodes.ts, packer/scripts/al2/al2-agent-setups.sh
Fix docker launch on the AL2
#188
=> Fix docker launch on the AL2

docker/plugins.txt
Blueocean plugin install.
https://github.com/opensearch-project/opensearch-ci/issues/195
=> Blueocean plugin install

lib/compute/agent-node-config.ts, lib/compute/agent-nodes.ts, packer/scripts/windows/userdata.ps1
Add more memory for winrm session on Windows
=> Add more memory for winrm session on Windows

resources/docker-compose.yml
Removes datetime format mismatch. 
=> Removed datetime format mismatch

lib/compute/agent-nodes.ts, packer/jenkins-agent-macos12-x64.json, packer/scripts/macos/macos-agentsetup.sh
Update amis to run from prod jenkins accounts
https://github.com/opensearch-project/opensearch-ci/issues/204
=> Update amis to run from prod jenkins accounts

lib/compute/agent-nodes.ts, packer/scripts/windows/scoop-install-commons.ps1
Add new node version 14.20.0 to Windows Agent
=> Add new node version 14.20.0 to Windows Agent

lib/compute/agent-nodes.ts, packer/scripts/windows/scoop-install-commons.ps1
Add new env var MINGW_BIN for k-NN
=> Add new env var MINGW_BIN for k-NN

lib/compute/agent-nodes.ts, packer/scripts/windows/scoop-install-commons.ps1, resources/baseJenkins.yaml, test/data/test_env.yaml
Add k-NN required zip and JDK19 for Core
https://github.com/opensearch-project/opensearch-build/pull/2808
=> Add k-NN required zip and JDK19 for Core

lib/monitoring/ci-alarms.ts
Signed-off-by: Prudhvi Godithi <pgodithi@amazon.com>
Change MainNodeJenkinsProcessNotFound alarm thresholds
https://github.com/opensearch-project/opensearch-ci/issues/217
=> Change MainNodeJenkinsProcessNotFound alarm thresholds

lib/compute/agent-nodes.ts, packer/scripts/windows/userdata.ps1
Raise Windows Runner Memory on WINRM configurations
https://github.com/opensearch-project/opensearch-build/issues/2966
=> Raise Windows Runner Memory on WINRM configurations

lib/ci-stack.ts, resources/cf-url-rewriter/package-lock.json, resources/cf-url-rewriter/package.json
Expose security group class variable to be used for cross-referencing. 
=> Expose security group class variable and remove license from url-rewriter package

lib/compute/agent-nodes.ts
Update ami for Ubuntu2004-X64-M52xlarge agent node. The ami is public. 
=> Update ami for Ubuntu2004-X64-M52xlarge agent node

lib/compute/agent-nodes.ts
=> updated ubuntu ami

lib/compute/run-additional-commands.ts
Update SSM Document and related association name
=> Update SSM Document and related association name

.whitesource
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
As WhiteSource didn't raise this onboard PR automatically, I'm manually raising this.
Welcome to [Mend for GitHub.com](https://github.com/apps/mend-for-github-com) (formerly WhiteSource). This is an onboarding PR to help you understand and configure settings before Mend starts scanning your repository for security vulnerabilities.
:vertical_traffic_light: Mend for GitHub.com will start scanning your repository only once you merge this Pull Request. To disable Mend for GitHub.com, simply close this Pull Request. 
---
This PR contains a '.whitesource' configuration file which can be customized to your needs. If no changes were applied to this file, Mend for GitHub.com will use the default configuration.
Before merging this PR, Make sure the …
=> Configure Mend for GitHub repo

lib/compute/agent-nodes.ts
Add grub in apt-mark so Ubuntu2004 wont update
#251
=> Add grub in apt-mark so Ubuntu2004 wont update

lib/compute/agent-nodes.ts
Add more spare instance on docker hosts
https://github.com/opensearch-project/opensearch-build/issues/2994
=> Add more spare instance on docker hosts

lib/compute/agent-nodes.ts, packer/scripts/al2/al2-agent-setups.sh
Add docker-compose on the single al2 agents
https://github.com/opensearch-project/opensearch-build/issues/2759
=> Add docker-compose on the single al2 agents

.github/CODEOWNERS, MAINTAINERS.md
Updated CODEOWNERS and maintainers list.
Closes #249 
=> Updating the MAINTAINERS.md and CODEOWNERS file

lib/security/ci-security-groups.ts, packer/jenkins-agent-al2-arm64.json, packer/jenkins-agent-al2-x64.json, packer/jenkins-agent-macos12-x64.json, packer/jenkins-agent-ubuntu2004-x64.json, packer/jenkins-agent-win2016-x64.json, packer/jenkins-agent-win2019-x64-alpine-wsl.json, packer/jenkins-agent-win2019-x64-gradle-check.json, packer/jenkins-agent-win2019-x64.json
Set all packer templates to use private ip
https://github.com/opensearch-project/opensearch-ci/issues/258
=> Set all packer templates to use private ip

packer/scripts/windows/scoop-install-commons.ps1
As called here:
https://github.com/opensearch-project/opensearch-build/pull/3356
Add the node version called out in our nvm file.
n/a
=> [OSD] update node version to include 14.21.3

lib/compute/agent-nodes.ts
Update windows to have the latest ami with nodejs 14.21.3
https://github.com/opensearch-project/opensearch-ci/pull/264
=> Update windows to have the latest ami with nodejs 14.21.3

packer/scripts/al2/al2-agent-setups.sh
Silent symlink error if link already exist in AL2 AMI
#267
=> Silent symlink error if link already exist in AL2 AMI

lib/compute/agent-nodes.ts
Add new AMIs for the 20230414 rebuilds
V880424506
=> Add new AMIs for the 20230414 rebuilds

lib/compute/run-additional-commands.ts
Updated SSM association with asg tag. 
=> Updated SSM association with asg tag

packer/scripts/al2/al2-agent-setups.sh
Resolve AL2 pip package path issues
https://github.com/opensearch-project/opensearch-build/issues/3201
=> Resolve AL2 pip package path issues

packer/scripts/al2/al2-agent-setups.sh
Add node and node packages required to run nightly performance benchmarking using opensearch-cluster-cdk and opensearch-benchmark. 
=> Add node and node packages in AL2

lib/compute/agent-nodes.ts
Tweak al2 agents to use pipenv fix ami in #282
#282
=> Tweak al2 agents to use pipenv fix ami in #282

packer/scripts/al2/al2-agent-setups.sh
Export path in al2 for pip
#282 
=> Export path in al2 for pip

lib/compute/agent-nodes.ts
Add #285 AL2 AMI in the agents
#285
=> Add #285 AL2 AMI in the agents

lib/ci-stack.ts, lib/compute/agent-nodes.ts, lib/compute/jenkins-main-node.ts, package-lock.json
Add dedicated benchmark agent. 
=> Add dedicated benchmark agent

lib/compute/agent-node-config.ts, packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh, packer/scripts/windows/scoop-install-commons.ps1
Support JDK-20 builds on Jenkins
Closes https://github.com/opensearch-project/opensearch-build/issues/3425
=> Support JDK-20 builds on Jenkins

lib/compute/agent-nodes.ts
Update windows ami updated in PR #291
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/408
=> Update windows ami updated in PR #291

lib/compute/agent-nodes.ts
Update windows ami id from #295
#295 
=> Update windows ami id from #295

lib/compute/agent-nodes.ts
Update AMI ID for Windows Agent in #298 #300
https://github.com/opensearch-project/opensearch-ci/issues/297
=> Update AMI ID for Windows Agent in #298 #300

docker/plugins.txt
Add support-core plugin. This plugin is required to generate workflow log file on disk. 
=> Add support-core plugin

lib/compute/agent-nodes.ts
Update agent node ami for windows in #301
Closes https://github.com/opensearch-project/opensearch-build/issues/3425
=> Update agent node ami for windows in #301

packer/scripts/macos/macos-agentsetup.sh, packer/scripts/windows/scoop-install-commons.ps1
[Python 3.9 Upgrade] Update macos and windows packer agent with Python 3.9
=> [Python 3.9 Upgrade] Update macos and windows packer agent with Python 3.9

lib/compute/agent-nodes.ts
Update Runner Ami IDs for Python 3.9 Upgrade
=> Update Runner Ami IDs for Python 3.9 Upgrade

lib/compute/agent-nodes.ts
[Python 3.9 Upgrade] [NodeJS Upgrade] Replace ami id for al2023 with agents in #319
=> [Python 3.9 Upgrade] [NodeJS Upgrade] Replace ami id for al2023 with agents in #319

lib/compute/agent-nodes.ts
[Python 3.9 Upgrade] Update macos runner ami id from #323
=> [Python 3.9 Upgrade] Update macos runner ami id from #323

lib/compute/agent-nodes.ts
Update AMIs for the month 20230718
Patching AMIs 20230718
=> Update AMIs for the month 20230718

lib/ci-stack.ts, lib/compute/agent-nodes.ts
Add AL2023 Docker Host Runner and Make M58xlarge Gradle Check Host
https://github.com/opensearch-project/opensearch-ci/issues/321
https://github.com/opensearch-project/opensearch-build/issues/3616
=> Add AL2023 Docker Host Runner and Make M58xlarge Gradle Check Host

MAINTAINERS.md
=> Add an Emeritus section

packer/scripts/windows/scoop-install-commons-docker-support.ps1
Add unzip and scoop clear cache in Windows
https://github.com/opensearch-project/opensearch-ci/issues/281
https://github.com/opensearch-project/opensearch-build/issues/3820
=> Add unzip and scoop clear cache in Windows

MAINTAINERS.md
=> Updating Emeritus table

lib/compute/agent-nodes.ts
Update ami ids for AL2023 selinux #351
https://github.com/opensearch-project/opensearch-build/issues/4047
=> Update ami ids for AL2023 selinux #351

lib/compute/agent-nodes.ts
Update ami id for windows runner gradle check from #356
#356
=> Update ami id for windows runner gradle check from #356

lib/compute/agent-nodes.ts
Add docker host required init script to gradle check windows runner
=> Add docker host required init script to gradle check windows runner

lib/compute/agent-nodes.ts
=> Add ami id from the PR #360

packer/jenkins-agent-win2019-x64-gradle-check.json, packer/jenkins-agent-win2019-x64.json
Switch back to c5.24large before further investigation0 on windows runner
=> Switch back to c5.24large before further investigation on windows runner

packer/jenkins-agent-win2019-x64-gradle-check.json, packer/jenkins-agent-win2019-x64.json
Make sure noshutdown settings is removed for windows instances
=> Make sure noshutdown settings is removed for windows instances

lib/compute/agent-nodes.ts
Update AMI from #363 and make sure AL2023 update latest pkgs
=> Update AMI from #363 and make sure AL2023 update latest pkgs

lib/compute/agent-nodes.ts, packer/jenkins-agent-win2019-x64-gradle-check.json
Restore all the way back to original c524xlarge as m58xlarge just not stable on Windows.
=> Restore all the way back to original c524xlarge as m58xlarge just not stable on Windows

lib/compute/agent-nodes.ts
Update Windows and Ubuntu ami ids
https://github.com/opensearch-project/opensearch-build/issues/4071
=> Update Windows and Ubuntu ami ids

packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
Ubuntu2004 update jdk installation steps per temurin website
https://github.com/opensearch-project/opensearch-build/issues/4071
=> Ubuntu2004 update jdk installation steps per temurin website

lib/compute/agent-nodes.ts
Update MAC Agent node AMI ID per the output of https://github.com/opensearch-project/opensearch-ci/pull/380
https://github.com/opensearch-project/opensearch-build/issues/4272
=> Update MAC agent node AMI Id to use 

lib/compute/jenkins-main-node.ts, test/compute/jenkins-main-node.test.ts
Jenkins CLI CVE https://www.jenkins.io/security/advisory/2024-01-24/ mitigation
https://github.com/opensearch-project/opensearch-ci/issues/386
=> Jenkins CLI CVE mitigation

packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
Resolve curl mv permission issues on ubuntu.
* To follow up https://github.com/opensearch-project/opensearch-ci/pull/406
https://github.com/opensearch-project/opensearch-build/issues/4469
=> Resolve curl mv permission issues on ubuntu

lib/compute/agent-nodes.ts
Update Windows docker host with AMI and M54xlarge from #417
https://github.com/opensearch-project/opensearch-ci/issues/412
=> Update Windows docker host with AMI and M54xlarge from #417

.github/CODEOWNERS, MAINTAINERS.md
@peterzhuamazon synced up with @jordarlu and concluded that he wishes to be moved to emeritus section.
=> Move jordarlu to emertius section

.github/CODEOWNERS, MAINTAINERS.md
Remove maintainer access for bbarani@
NA
=> Remove maintainer access for bbarani@

lib/compute/agent-nodes.ts
Reduce Windows script 127 issues after switching from servercore to server images
https://github.com/opensearch-project/opensearch-ci/issues/412
=> Reduce Windows script 127 issues after switching from servercore to server images

.github/workflows/packer.yml, packer/jenkins-agent-al2-arm64.json, packer/jenkins-agent-al2-x64.json, packer/jenkins-agent-al2023-arm64.json, packer/jenkins-agent-al2023-x64.json, packer/jenkins-agent-macos12-x64.json, packer/jenkins-agent-ubuntu2004-x64.json, packer/jenkins-agent-win2019-x64-gradle-check.json, packer/jenkins-agent-win2019-x64.json
Add packer validate github check workflow
Closes https://github.com/opensearch-project/opensearch-ci/issues/438
=> Add packer validate github check workflow

lib/compute/jenkins-main-node.ts, test/compute/jenkins-main-node.test.ts
Add missing jdk changes from al2023 update
Closes https://github.com/opensearch-project/opensearch-ci/issues/476
=> Add missing jdk changes from al2023 update

lib/compute/agent-nodes.ts
Update Ubuntu AMI to the latest builds
https://github.com/opensearch-project/opensearch-build/issues/4771
=> Update Ubuntu AMI to the latest builds

lib/compute/jenkins-main-node.ts
Switch to ELASTIC mode for the EFS
https://github.com/opensearch-project/opensearch-build/issues/4771
=> Switch to ELASTIC mode for the EFS

lib/compute/agent-nodes.ts
Switch AL2023 to latest AMI builds 20240725
https://github.com/opensearch-project/opensearch-build/issues/4771
=> Switch AL2023 to latest AMI builds 20240725

packer/scripts/macos/macos-agentsetup.sh
Cleanup macos ami to reduce size
=> Cleanup macos ami to reduce size

packer/scripts/al2023/al2023-agent-setups.sh
Upgrade packaging to latest version to avoid tailing 0 issues
https://github.com/opensearch-project/opensearch-build/issues/4929
=> Upgrade packaging to latest version to avoid tailing 0 issues

lib/compute/agent-nodes.ts
Update AL2023 AMI with latest build of 20240808
Closes https://github.com/opensearch-project/opensearch-build/issues/4929
=> Update AL2023 AMI with latest build of 20240808

packer/scripts/al2/al2-agent-setups.sh, packer/scripts/al2023/al2023-agent-setups.sh
Ensure docker==6.1.3 and requests==2.28.1 to support docker-compose v1
https://github.com/opensearch-project/opensearch-build/issues/4946
=> Ensure docker==6.1.3 and requests==2.28.1 to support docker-compose v1

lib/compute/agent-nodes.ts
Update AL2023 AMI id from 20240813 changes in #490
Closes https://github.com/opensearch-project/opensearch-build/issues/4946
=> Update AL2023 AMI id from 20240813 changes in #490

lib/compute/agent-nodes.ts
Reduce executors per agent for integeration test in order to allow more memory for docker images
=> Reduce executors per agent for integeration test

packer/scripts/macos/macos-agentsetup.sh
Adding gnupg to the macos agents for signature verifications
Closes https://github.com/opensearch-project/opensearch-build/issues/5096#issuecomment-2465741202
=> Adding gnupg to the macos agents for signature verifications

packer/scripts/windows/scoop-setup.ps1
Switch scoop installation to 0.4.2 version
Similar to https://github.com/opensearch-project/opensearch-build/pull/5093
=> Switch scoop installation to 0.4.2 version

lib/compute/agent-node-config.ts, lib/compute/agent-nodes.ts
Replace #525 Windows AMI and extend startup time
Closes https://github.com/opensearch-project/opensearch-ci/issues/523
=> Replace #525 Windows AMI and extend startup time

lib/network/ci-external-load-balancer.ts
Update ALB to use RECOMMENDED_TLS SslPolicy to remove TLS1.1
=> Update ALB to use RECOMMENDED_TLS SslPolicy to remove TLS1.1

lib/compute/agent-nodes.ts
Update Ubuntu2404 image ami id on #533
https://github.com/opensearch-project/opensearch-build/issues/5270
https://github.com/opensearch-project/opensearch-build/issues/3747
=> Update Ubuntu2404 image ami id on #533

lib/compute/auth-config.ts, test/compute/auth-config.test.ts
Switch readonly access from anonymous to authenticated users.
=> Switch readonly access from anonymous to authenticated users

lib/compute/agent-nodes.ts, test/ci-stack.test.ts
Update ami ids value with jdk24 runners
https://github.com/opensearch-project/opensearch-ci/pull/552
=> Update ami ids value with jdk24 runners

.github/workflows/deploy-stacks.yml, test/compute/agent-node-config.test.ts
=> fix workflow syntax

lib/compute/agent-nodes.ts, test/ci-stack.test.ts
Add decdicated agent for vectorsearch benchmarking job. 
=> add decdicated agent for vectorsearch benchmarking job

.github/workflows/deploy-stacks.yml
The credentials setup should be before fetching the stack diff. 
=> minor bug fix in deploy workflow

lib/secrets/secret-credentials.ts, test/ci-stack.test.ts
Add remote index images webhook token
https://github.com/opensearch-project/.github/issues/344
=> Add remote index images webhook token

bin/ci-stack.ts
Allow bot to run release chores
https://github.com/opensearch-project/opensearch-build/issues/5700
=> Allow bot to run release chores
