README.md
lib/ci-stack.ts
lib/compute/jenkins-main-node.ts

Adding a strict mode to make sure that cloud-init passes during the
deployment for environments that need more rigor.
Signed-off-by: Peter Nied <petern@amazon.com>

Strict deployment mode

---

lib/compute/jenkins-main-node.ts
test/compute/jenkins-main-node.test.ts

Auto redirect http to https when SSL is enabled
#68 

Fix auto redirect for http when SSL is enabled

---

lib/network/ci-external-load-balancer.ts
lib/security/ci-security-groups.ts

After #69 the issue for redirection still existed. This change fixes that.
Deployed the stack with self signed certs and tried http://url. It auto-redirected to https
Resolves #68 

Load balancer changes for http to https redirection

---

lib/network/ci-external-load-balancer.ts

Signed-off-by: Abhinav Gupta <abhng@amazon.com>
set ssl policy to be null when useSsl is false
deploy with ssl false failed

set ssl policy to be undefined when useSsl is false

---

README.md
lib/ci-stack.ts
lib/compute/jenkins-main-node-config.ts
lib/compute/jenkins-main-node.ts
test/compute/jenkins-main-node-config.test.ts
test/compute/jenkins-main-node.test.ts

When OIDC is enabled the user is locked out as no one has admin access now. This PR fixes the issue and gives a set of users admin access.
N/A

Enable Role Based Authentication when OIDC is enabled

---

lib/compute/jenkins-main-node.ts
test/compute/jenkins-main-node.test.ts

Once OIDC is active, none of the admin based command lines work. This PR changes the order in which config is added to config.xml file. OIDC will be activated at last once all other config (example: agent node config) is in.

Restructure OIDC element

---

README.md
lib/compute/jenkins-main-node.ts

Due to the wrong key value in README OIDC password was being set as null causing OIDC to fail. This PR fixes this. 
The change in sleep seconds is to trigger a redeploy to internal stack.

Fix README

---

lib/compute/agent-nodes.ts
lib/compute/jenkins-plugins.ts

Signed-off-by: Abhinav Gupta <abhng@amazon.com>
ci can now run docker agent nodes and withAws commands
https://github.com/opensearch-project/opensearch-ci/issues/79

update jenkins deployment to use docker on agent nodes

---

lib/compute/jenkins-main-node.ts
lib/compute/jenkins-plugins.ts

The multi-SCM plugin is deprecated and is causing null pointer errors in few actions in Jenkins. Removing this plugin as it is not required anymore.
https://plugins.jenkins.io/multiple-scms/
N/A

Remove multi-scm plugin

---

.gitignore
bin/ci-stack.ts
lib/ci-stack.ts
lib/compute/agent-node-config.ts
lib/compute/agent-nodes.ts
lib/compute/jenkins-main-node.ts
lib/compute/oidc-config.ts
test/compute/oidc-config.test.ts

This change adds the functionality to load agent nodes configuration via jenkins.yaml
Tested by deploying the stack using all combinations(ssl/oidc: true/false) to make sure none of the other functionality breaks.
Resolves #88 

[Agent Nodes] Load jenkins config via yaml

---

lib/compute/oidc-config.ts

There was a mismatch in the OIDC values compared to the one pushed in older PR: https://github.com/abhinavGupta16/opensearch-ci/blob/6778f6ab19d5e725627704b2b1eba8aa99637b1c/lib/compute/jenkins-main-node.ts#L355-L366
This PR fixes that.

Fix OIDC values

---

lib/compute/oidc-config.ts

Looking https://github.com/abhinavGupta16/opensearch-ci/blob/6778f6ab19d5e725627704b2b1eba8aa99637b1c/lib/compute/jenkins-main-node.ts#L354-L366 keeping only those values and also fixing the typo for anonymous

Fix typo and keep previous values for OIDC

---

lib/ci-stack.ts
lib/compute/jenkins-main-node.ts
lib/compute/oidc-config.ts
test/compute/jenkins-main-node.test.ts

Strict Mode was not doing what it says, when user was setting `strictMode: true` in reality, the error were ignored (during init commands). This PR fixes the words to better understand the functionality behind it.
Also removed jq installation as it is not used anywhere

Rename strict mode to ignoreResourcesFailures and remove jq installation

---

lib/compute/jenkins-main-node.ts
resources/baseJenkins.yaml
resources/docker-compose.yml
test/compute/jenkins-main-node.test.ts

- Add additional permission for EFS mount points look up
- Fix logging for docker compose
- Add conditional init commands to check jenkins availability

Fix EFS permissions, logging and init commands

---

lib/ci-stack.ts
lib/compute/jenkins-main-node.ts
lib/monitoring/ci-alarms.ts

Updated monitoring stack's variable scope to instance level in order to be used by consuming packages for various use-cases, e.g., using CW Alarms to create monitors using 3P tools. 
Related to meta issue #2 

changed variable scope to instance level

---

lib/compute/agent-node-config.ts

Currently the role attached to Jenkins agent EC2 node does not have any policy associated with it. This PR adds managed SSM Policy to the instance role. This policy is required to run bare minimum access to make sure the instance is reporting to internal audit tool and helps doing patch baselining.
#116 

Added Managed SSM Policy to Agent instance role

---

.github/workflows/docker.yml
docker/Dockerfile
resources/docker-compose.yml

This PR adds support to use `jenkins/jenkins:2.332.3-lts-jdk8` as base image instead of `jenkins/jenkins:2.332.3-lts` which is jdk11 based image. A few aws-java-sdk functions are not supported by jdk9+ and are only supported till jdk8. 

use jenkins-2.332.3 jdk8 base image

---

resources/baseJenkins.yaml

Add markup formatter as safe/html disable syntax highlighting to allow html
Part of https://github.com/opensearch-project/opensearch-build/issues/851
* Settings:
* Before:
* After:

Add markup formatter as safe/html disable syntax highlighting to allow html

---

resources/baseJenkins.yaml

Set cache to false for aws secret manager plugin

Set cache to false for aws secret manager plugin

---

lib/compute/env-config.ts
test/compute/env-config.test.ts
test/data/env.txt
test/data/test_env.yaml

This PR fixes the bug where if multiple colons (:) are present the split method will only split the first occurrence of it.
Also handles the use case where use enters multiple spaces in between key value pairs.
Also added the test cases to check.

[Bug-fix]: Handle multiple colons and space

---

README.md
lib/compute/env-config.ts
test/compute/env-config.test.ts
test/data/env.txt
test/data/env.yaml
test/data/test_env.yaml

Since env variables are key value pair, accepting them in the form of a yaml file instead of txt file

Move env variabled to yaml

---

README.md
lib/ci-config-stack.ts
lib/ci-stack.ts
lib/compute/jenkins-main-node.ts
resources/docker-compose.yml
test/compute/jenkins-main-node.test.ts

We were seeing issues with reload command via cli in our [codebase](https://github.com/opensearch-project/opensearch-ci/blob/main/lib/compute/jenkins-main-node.ts#L393) randomly returning error code as 255 even if the command was successful. 
This lead to fail of deployment. This PR fixes the need to reload via cli and instead reload using post method of curl. Looks much more secure as it uses a user provided password to reload config. 
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/configurationReload.md
For more information on …

Reload configuration as code via curl instead of cli

---

lib/ci-stack.ts
lib/compute/agent-node-config.ts
lib/compute/agent-nodes.ts
resources/baseJenkins.yaml
test/data/test_env.yaml

Add Ubuntu Single Host for Gradle Check
https://github.com/opensearch-project/opensearch-build/issues/851

Add Ubuntu Single Host for Gradle Check

---

resources/baseJenkins.yaml
test/data/test_env.yaml

Add jdk14 as it is required by OS 1.x gradle check
https://github.com/opensearch-project/opensearch-build/issues/851

Add jdk14 as it is required by OS 1.x gradle check

---

lib/ci-stack.ts
lib/compute/agent-nodes.ts

Migrate perf test agent setups to public jenkins
Part of https://github.com/opensearch-project/opensearch-ci/issues/132

Migrate perf test agent setups to public jenkins

---

resources/baseJenkins.yaml
test/data/test_env.yaml

Make jenkins jdk tool match manifest jdk naming
Part of #2362, https://github.com/opensearch-project/opensearch-build/pull/2365

Make jenkins jdk tool match manifest jdk naming

---

lib/compute/agent-nodes.ts
lib/compute/jenkins-main-node.ts

1. 
In this PR: https://github.com/opensearch-project/opensearch-ci/commit/c2f5e810a61778382d83382346806c6a88243494, docker-compose was mistakenly removed thus failed the run:
https://build.ci.opensearch.org/job/gradle-check/1024/console
This PR fix both of these issues.

Fix gradle check by removing old caches and add back docker-compose

---

lib/compute/jenkins-main-node.ts
lib/monitoring/ci-alarms.ts
test/ci-stack.test.ts

This PR is to update the metric stat from `max` to `avg` for jenkins process cpu and memory utilization. 
Also updated the `procstat` metric patter to `Djenkins` as there are to process running on the instance that contain the keyword `jenkins`. 
```
[root@ip-10-0-138-75 ~]# ps aux|grep -v grep|grep jenkins
root      5873  0.0  0.0   1152     4 pts/0    Ss   13:24   0:00 /sbin/tini -- /usr/local/bin/jenkins.sh
root      5953  4.9 10.2 17853440 3307496 pts/0 Sl+ 13:24   1:21 java -Duser.home=/var/jenkins_home -Djenkins.install.runSetupWizard=false -Xmx8g -Djenkins.model.Jenkins.slaveAgentPort=50000 -Dhudson.lifecycle=hudson.lifecycle.ExitLifecycle -jar /usr/share/jenkins/jenkins.war
``` 
By submitting this pull request, I confirm that my …

Changed cpu and memory metric stat to avg

---

lib/ci-stack.ts
lib/compute/agent-node-config.ts
lib/compute/jenkins-main-node.ts
test/compute/agent-node-config.test.ts

A single agent node role might need to assume multiple roles across different accounts. This PR adds that functionality.
Also removes policy name that causes conflict during multiple deployments.

Add ability to assume multiple roles

---

lib/compute/jenkins-main-node.ts
lib/monitoring/ci-alarms.ts
test/ci-stack.test.ts

This PR adds CW Alarm on overall average cpu utilization of jenkins main node instance. 

added alarm on avg cpu utilization of ec2 instance

---

lib/compute/agent-node-config.ts
lib/compute/agent-nodes.ts
packer/jenkins-agent-win2019-x64.json
packer/scripts/windows/longpath-setup.ps1
packer/scripts/windows/scoop-install-commons.ps1

Tweaks to windows agent to support distribution builds

Tweaks to windows agent to support distribution builds

---

lib/compute/agent-nodes.ts
packer/scripts/windows/scoop-install-commons.ps1

Fix malloc issues on windows agent
https://github.com/opensearch-project/opensearch-build/issues/2306#issuecomment-1226263646

Fix malloc issues on windows agent

---

lib/compute/agent-nodes.ts
packer/scripts/windows/scoop-install-commons.ps1

New configurations to windows git to prevent random mem issues

New configurations to windows git to prevent random mem issues

---

lib/compute/agent-nodes.ts

Fix gh upgrade changing pgp keys
```
(3/3): gh_2.15.0_linux_arm64.rpm                           | 7.0 MB   00:00     
--------------------------------------------------------------------------------
Total                                               65 MB/s | 7.6 MB  00:00     
Retrieving key from https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc99b11deb97541f0
The GPG keys listed for the "packages for the GitHub CLI" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.
Failing package is: gh-2.15.0-1.aarch64
GPG Keys are configured as: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xc99b11deb97541f0
Sep 06, 2022 6:33:19 PM …
```

Fix gh upgrade changing pgp keys

---

resources/baseJenkins.yaml
test/data/test_env.yaml

Update JDK14 to use zip installer as Jenkins has stopped support
https://github.com/opensearch-project/opensearch-build/issues/2604

Update JDK14 to use zip installer as Jenkins has stopped support

---

lib/compute/agent-nodes.ts
packer/scripts/windows/scoop-install-commons.ps1

Add mingw related changes to Windows Agents
https://github.com/opensearch-project/k-NN/issues/157#issuecomment-1245817651

Add mingw related changes to Windows Agents

---

lib/compute/agent-nodes.ts

Restore maxrun of windows agent to unlimited

Restore maxrun of windows agent to unlimited

---

packer/scripts/windows/scoop-install-commons.ps1

Replace nvm with volta for Windows Agent.
Volta has fixed path regardless of which nodejs version it is switching to, therefore more suitable for windows env as we can simply define the path through env vars. NVM use symlink to switch version which does not preserve during the windows ami creation.

Replace nvm with volta for Windows Agent

---

lib/ci-stack.ts
lib/compute/agent-nodes.ts
packer/scripts/windows/scoop-install-commons.ps1

Add Windows Gradle Check Jenkins Agent
https://github.com/opensearch-project/OpenSearch/issues/4817

Add Windows Gradle Check Jenkins Agent

---

lib/compute/agent-nodes.ts

Restore windows to use 1 executor max
Recent checks shows that if there are two or more executors get a hook on bash.exe, while trying to deploy to mavenlocal, which is `C:\\Users\\Administrator\\.m2` the second process will not be able to access. The folder has to be forcefully removed before a second process can take over. Seems like some types of protection lock on Windows, since we are not having docker windows on windows.
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':client:test:publishNebulaPublicationToMavenLocal'.
> Failed to publish publication 'nebula' to repository 'mavenLocal'
> Could not write to resource 'file:/C:/Users/Administrator/.m2/repository/org/opensearch/client/test/test/2.4. …
```

Restore windows to use 1 executor max

---

lib/compute/agent-nodes.ts
packer/scripts/windows/scoop-install-commons.ps1

Resolve incorrectly added env vars for Windows

Resolve incorrectly added env vars for Windows

---

lib/compute/agent-node-config.ts
resources/baseJenkins.yaml
test/data/test_env.yaml

Add JENKINS_HOME_PATH as default JENKINS_HOME always returns /var/jenkins_home.
This is a backend settings required to support windows gradle check.
Due to LINUX and Windows having different home directory for Jenkins, we need a variable to export the value.
The issue is, the default JENKINS_HOME variable is always returning `/var/jenkins_home` regardless of the platform.
By adding a node var for the agents it will dynamically display the root based on the platform remote fs.
Thanks.
For more information on following Developer Certificate of Origin and signing off …

Add JENKINS_HOME_PATH as default JENKINS_HOME always returns /var/jenkins_home

---

lib/compute/jenkins-main-node.ts
lib/monitoring/ci-alarms.ts

Signed-off-by: Prudhvi Godithi <pgodithi@amazon.com>
Fix cloudwatch alarm `MainNodeTooManyJenkinsProcessesFound` to `MainNodeJenkinsProcessNotFound`
https://github.com/opensearch-project/opensearch-ci/issues/217

Bug: Fix cloudwatch alarm `MainNodeTooManyJenkinsProcessesFound`

---

lib/compute/agent-nodes.ts
packer/jenkins-agent-al2-arm64.json
packer/jenkins-agent-al2-x64.json
packer/jenkins-agent-macos12-x64.json
packer/jenkins-agent-ubuntu2004-x64.json
packer/jenkins-agent-win2016-x64.json
packer/jenkins-agent-win2019-x64-alpine-wsl.json
packer/jenkins-agent-win2019-x64.json
packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
resources/baseJenkins.yaml

Remove jdk14 live installation and relies on pre-installed AMIs while fix gradle check issues.

Remove jdk14 live installation and relies on pre-installed AMIs while fix gradle check issues

---

lib/compute/agent-nodes.ts

Update ami for ubuntu to use latest gradle check images

Update ami for ubuntu to use latest gradle check images

---

lib/compute/agent-node-config.ts
lib/compute/agent-nodes.ts
packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
packer/scripts/windows/scoop-install-commons.ps1

Add agent node changes to support windows gradle check
https://github.com/opensearch-project/OpenSearch/issues/4817
https://github.com/opensearch-project/OpenSearch/issues/4811

Add agent node changes to support windows gradle check

---

README.md
lib/ci-stack.ts
lib/security/ci-security-groups.ts
test/ci-stack.test.ts
test/compute/agent-node-config.test.ts

This change enforces the user of this CDK to specify what kind of access they want to give to their jenkins server. There are no defaults.

Enforce jenkins server access

---

lib/monitoring/ci-alarms.ts
test/ci-stack.test.ts

Remove cloudwatch agent monitoring alarm. This alarm is irrelevant is giving false negative alarms. If cloudwatch agent stops all other alarms will go off automatically. Hence this one is not required.

Remove cloudwatch agent monitoring alarm

---

lib/monitoring/ci-alarms.ts

Signed-off-by: Prudhvi Godithi <pgodithi@amazon.com>
Update MainNodeHighMemoryUtilization Alarm threshold to 65

Update MainNodeHighMemoryUtilization Alarm threshold to 65

---

resources/baseJenkins.yaml
test/data/test_env.yaml

Fix authorization strategy for default config. The default config was setting `Anyone can do anything` which was dangerous. This PR fixes that and only allows logged in user to go anything by default if OIDC is disabled. 

Fix authorization strategy for default config

---

lib/compute/run-additional-commands.ts

Append current datestamp to SSM document name to avoid update failures

Append current datestamp to SSM document name to avoid update failures

---

lib/compute/agent-nodes.ts
packer/jenkins-agent-win2019-x64-gradle-check.json
packer/scripts/windows/longpath-setup.ps1
packer/scripts/windows/pip-install.ps1
packer/scripts/windows/scoop-install-alpinewsl.ps1
packer/scripts/windows/scoop-install-commons.ps1
packer/scripts/windows/scoop-setup.ps1
packer/scripts/windows/smb-setup-2019-plus.ps1
packer/scripts/windows/smb-setup.ps1
packer/scripts/windows/userdata.ps1
packer/scripts/windows/winrm_max_memory.ps1
packer/scripts/windows/wsl-setup.ps1

Make windows gradle check server using proper amount of memory in WinRM
https://github.com/opensearch-project/opensearch-build-libraries/issues/113

Make windows gradle check server using proper amount of memory in WinRM

---

.gitignore
lib/compute/agent-nodes.ts

Recently the CI system faced an issues where shim-signed package was unable to upgrade. 
```
Setting up shim-signed (1.40.9+15.7-0ubuntu1) ...
mount: /var/lib/grub/esp: special device /dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol0f36dbf39c1951023-part15 does not exist.
dpkg: error processing package shim-signed (--configure):
installed shim-signed package post-installation script subprocess returned error exit status 32
Errors were encountered while processing:
shim-signed
E: Sub-process /usr/bin/dpkg returned an error code (1)
Mar 14, 2023 9:52:30 PM hudson.plugins.ec2.EC2Cloud
WARNING: init script failed: exit code=100
```
This might be due to dependent package being on hold as well which is grub-efi
Ref: https://bugs.launchpad.net/ubuntu/+source/shim-signed/+bug/1940723
This …

Hold apt upgrade for shim-signed

---

lib/compute/agent-nodes.ts
packer/scripts/windows/scoop-install-commons.ps1

Windows mingw lock on to non-ucrt version to resolve knn crash jvm issue
https://github.com/opensearch-project/k-NN/issues/829#issuecomment-1499846457
https://github.com/opensearch-project/opensearch-build/issues/3230

Windows mingw lock on to non-ucrt version to resolve knn crash jvm issue

---

.github/workflows/docker.yml
docker/Dockerfile
docker/plugins.txt

This change will build new docker image with `jenkins/jenkins:2.387.1-lts-jdk11` as base. Also install all plugins as part of it 
part of #260 

[Upgrade Jenkins] Upgrade jenkins docker image

---

packer/scripts/al2/al2-agent-setups.sh
packer/scripts/macos/macos-agentsetup.sh
packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
packer/scripts/windows/scoop-install-commons.ps1

Switch to java 11 as default java version on agent nodes. Required for newer jenkins version.
Ubuntu: Contains everything as before but default changed to java 11
Windows: Contains everything as before but default changed to java 11
MacOS: Contains only java 11 now
AL2: Contains only java 11 now
Part of #260 

[Upgrade jenkins] Switch to java 11 as default java version on agent nodes

---

lib/auditing/ci-audit-logging.ts
lib/compute/agent-nodes.ts
lib/compute/jenkins-main-node.ts
package.json
resources/docker-compose.yml
test/compute/jenkins-main-node.test.ts

- Upgrade jenkins to 2.387.1
- Use new AMIs that has java 11 as default. Confirmed that all AMIs are public.
- Bump package version to 0.3.0
- Enable detail monitoring for main node
- With recent change in S3 bucket ownership, added change in ownership which resolves below error:
```
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership;
```
resolves #261
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of …

Upgrade jenkins to 2.387.1

---

packer/scripts/windows/scoop-install-alpinewsl.ps1
packer/scripts/windows/scoop-install-commons.ps1

Add chromium installation to the windows ami
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/408
https://github.com/opensearch-project/opensearch-build/issues/3196

Add chromium installation to the windows ami

---

packer/scripts/windows/scoop-install-commons.ps1

Replace temurin20 with openjdk20 as former is not available on Windows
https://github.com/opensearch-project/opensearch-build/issues/3425

Replace temurin20 with openjdk20 as former is not available on Windows

---

packer/scripts/windows/scoop-install-commons.ps1

Correct chromium path found in Windows
https://github.com/opensearch-project/opensearch-build/issues/3425

Correct chromium path found in Windows

---

lib/compute/jenkins-main-node.ts
lib/constructs/cloudwatch-agent.ts
lib/constructs/cloudwatch/logs-section.ts
resources/baseJenkins.yaml
test/compute/env-config.test.ts
test/data/test_env.yaml

The jenkins upgrade broke the logging for workflow runs that is required for monitoring. This PR adds the workflow run custom loggers and accordingly cloudwatch log group as well as logstream.
Will create a new logging file under `/var/lib/jenkins/logs/custom` called as `workflowRun.log`
Also creates cloudwatch log group called `JenkinsMainNode/workflow.log` with log stream named `workflow-logs`
resolves https://github.com/opensearch-project/opensearch-ci/issues/290
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-o …

[Bug fix] Add logging for workflow runs

---

lib/compute/agent-nodes.ts

Reduce # of executors for benchmark agent to 2. There has been situation when there were 4 instances of `nyc_taxis` workload was running on one node resulting in `not enough disk space` error as each instance tries to download ~75gb of data. 
This also spikes the disk I/O resulting in degraded performance of benchmarking process. 
Running with 2 executors has shown significant improvement.  

Reduce # of executors for benchmark agent to 2

---

packer/scripts/windows/scoop-install-commons.ps1
resources/baseJenkins.yaml

Resolve Windows chromium path and add jdk20 tool on Jenkins
Closes https://github.com/opensearch-project/opensearch-build/issues/3425

Resolve Windows chromium path and add jdk20 tool on Jenkins

---

packer/scripts/windows/scoop-install-commons.ps1

[Python 3.9 Upgrade] Lock Windows Python to 3.9.7 and cmake to 3.21.3 (Part 2) #313 

[Python 3.9 Upgrade] Lock Windows Python to 3.9.7 and cmake to 3.21.3 (Part 2)

---

packer/scripts/windows/scoop-install-commons.ps1

[Python 3.9 Upgrade] Restore python39 back to latest version due to old json not supported on scoop for 3.9.7 anymore

[Python 3.9 Upgrade] Restore python39 back to latest version due to old json not supported on scoop for 3.9.7 anymore

---

packer/jenkins-agent-al2023-arm64.json
packer/jenkins-agent-al2023-x64.json

[Python 3.9 Upgrade] [NodeJS Upgrade] Switch the internal ami name from al2 to al2023

[Python 3.9 Upgrade] [NodeJS Upgrade] Switch the internal ami name from al2 to al2023

---

lib/ci-stack.ts
lib/compute/agent-nodes.ts
packer/files/macos/bashrc

Update macos agent to Python 3.9 export and add M58xlarge gradle check runner
https://github.com/opensearch-project/opensearch-ci/issues/321

[Python 3.9 Upgrade] Update macos agent to Python 3.9 export and add M58xlarge gradle check runner

---

packer/scripts/macos/macos-agentsetup.sh
packer/scripts/windows/scoop-install-commons.ps1

Update cmake to 3.23.3 for k-NN in 2.9.0 in AMIs
https://github.com/opensearch-project/opensearch-build/issues/3706

Update cmake to 3.23.3 for k-NN in 2.9.0 in AMIs

---

lib/compute/agent-nodes.ts

Update the new macos/windows ami ids with cmake upgrade 3.23.3 in #324
https://github.com/opensearch-project/opensearch-build/issues/3706

Update the new macos/windows ami ids with cmake upgrade 3.23.3 in #324

---

lib/ci-stack.ts
lib/compute/agent-nodes.ts

Switch single host from AL2 to AL2023
https://github.com/opensearch-project/opensearch-build/issues/3616

Switch single host from AL2 to AL2023

---

packer/scripts/windows/scoop-install-commons-docker-support.ps1

Replace gzip with pigz for Windows docker extraction
https://github.com/opensearch-project/opensearch-ci/issues/281
[opensearch-project/opensearch-build#3820](https://github.com/opensearch-project/opensearch-build/issues/3820)

Replace gzip with pigz for Windows docker extraction

---

lib/compute/jenkins-main-node.ts
test/compute/jenkins-main-node.test.ts

We had already enabled IMDSv2 on all agent nodes before in order to make secure calls to instance metadata. See https://github.com/opensearch-project/opensearch-ci/pull/273.
This change enables the same on main node. 

Enable IMDSv2 on jenkins main node

---

lib/ci-stack.ts
lib/compute/agent-nodes.ts
packer/scripts/windows/scoop-install-commons-docker-support.ps1

[NodeJS18 Upgrade] Remove old AL2 Docker Host and Tweak Windows Startup Scripts

[NodeJS18 Upgrade] Remove old AL2 Docker Host and Tweak Windows Startup Scripts

---

lib/compute/agent-nodes.ts

[Windows Container] Update AMI ID from PR Number #342

[Windows Container] Update AMI ID from PR Number #342

---

lib/compute/agent-nodes.ts

[Windows Container] Remove interactive shell so Windows AMI can start properly
https://github.com/opensearch-project/opensearch-ci/issues/281

[Windows Container] Remove interactive shell so Windows AMI can start properly

---

lib/compute/agent-nodes.ts

[NodeJS18 Upgrade] [Windows Container] Adjust spare instance number for AL2023 and Windows Docker Host
https://github.com/opensearch-project/opensearch-ci/issues/281

[NodeJS18 Upgrade] [Windows Container] Adjust spare instance number for AL2023 and Windows Docker Host

---

lib/compute/jenkins-main-node.ts
resources/docker-compose.yml
test/ci-stack.test.ts

Replace c54xlarge instance with c59xlarge on Jenkins Main Node
https://github.com/opensearch-project/opensearch-ci/issues/346

Replace c54xlarge instance with c59xlarge on Jenkins Main Node

---

resources/docker-compose.yml

Remove quotes around JENKINS_JAVA_OPTS to allow multiple entries
Closes https://github.com/opensearch-project/opensearch-ci/issues/346

Remove quotes around JENKINS_JAVA_OPTS to allow multiple entries

---

packer/scripts/al2023/al2023-agent-setups.sh

Disable selinux by default on AL2023 Host
https://github.com/opensearch-project/opensearch-build/issues/4047

Disable selinux by default on AL2023 Host

---

resources/docker-compose.yml

Improve jenkins performance, this should address the jenkins 504 timeout errors due to `OutOfMemoryError`
Part of https://github.com/opensearch-project/opensearch-ci/issues/346
**Analysis-1**
Started to Debug with created a 360 java heap dump using an open source [yc tool](https://github.com/ycrash/yc-data-script).
Extracted the yc-2023-09-29T04-32-09.zip and used jhat cli debug the heap dump, noted error as: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space.
Also analyzed all the dump files part of the zip and found out multiple threads in `BLOCKED` state each honoring the setting `-Xss4m`.
Apart form having the threads in `BLOCKED` state. noted multiple `I/O` errors with threads interrupted state.
**Took some measures to fix this.**
* Removed the `-Xss` setting to …

Improve jenkins performance

---

packer/jenkins-agent-win2019-x64-gradle-check.json

Switch Windows gradle check runner from C524large to M58xlarge matching LINUX

Switch Windows gradle check runner from C524large to M58xlarge matching LINUX

---

lib/ci-stack.ts
lib/compute/agent-nodes.ts

Remove old Windows runner and replace Windows Gradle Check Runner AMI ID with M58xlarge

Remove old Windows runner and replace Windows Gradle Check Runner AMI ID with M58xlarge

---

packer/jenkins-agent-win2019-x64-gradle-check.json

Make sure windows gradle check runner is supporting docker

Make sure windows gradle check runner is supporting docker

---

packer/jenkins-agent-win2019-x64-gradle-check.json
packer/jenkins-agent-win2019-x64.json
packer/scripts/windows/winrm_max_memory.ps1

Update Windows Gradle Check Runner to use 126GB WINRM Mem on M58xlarge

Update Windows Gradle Check Runner to use 126GB WINRM Mem on M58xlarge

---

packer/jenkins-agent-win2019-x64-gradle-check.json
packer/scripts/windows/winrm_max_memory.ps1

Make sure only 110G mem is utilized for WINRM M58xlarge on Windows Gradle Check Runner

Make sure only 110G mem is utilized for WINRM M58xlarge on Windows Gradle Check Runner

---

resources/docker-compose.yml

Adjust min and max heap to 4G and 16G. 
https://github.com/opensearch-project/opensearch-build/issues/4130

Adjust min and max heap to 4G and 16G

---

lib/compute/agent-node-config.ts
packer/jenkins-agent-win2019-x64-gradle-check.json
packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
packer/scripts/windows/legacy/scoop-install-commons.ps1
resources/baseJenkins.yaml

Restore old windows runner for gradle and update jdk21

Restore old windows runner for gradle and update jdk21

---

lib/compute/agent-nodes.ts

Reset the windows runner label to C524large and update AMI #369

Reset the windows runner label to C524large and update AMI

---

lib/compute/agent-nodes.ts

Get ubuntu amis update to latest with jdk21
https://github.com/opensearch-project/opensearch-build/issues/4071

Get ubuntu amis update to latest with jdk21

---

packer/scripts/macos/macos-agentsetup.sh

- Adding JDK8, JDK14, JDK17, JDK19, JDK20, and JDK21 on Jenkins MAC agent node setup shell script
- Set default JAVA to JDK11 
ref : https://ports.macports.org/port/openjdk11-temurin/details/ 
A Mac agent build failure on JDK21 (https://build.ci.opensearch.org/blue/organizations/jenkins/publish-opensearch-min-snapshots/detail/publish-opensearch-min-snapshots/432/pipeline) due to a bug (https://github.com/opensearch-project/opensearch-build/issues/4272) 

Adding more JDK support for Jenkins Mac agent nodes 

---

lib/compute/agent-nodes.ts

Update MAC agent nodes AMI ID with newly created one from packer https://build.ci.opensearch.org/blue/organizations/jenkins/packer-build/detail/packer-build/91/pipeline/
current - https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Images:visibility=public-images;imageId=ami-0a5f5363c1db8ff67
new - https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Images:visibility=public-images;imageId=ami-0e88d55f1ab4bd51d
part of https://github.com/opensearch-project/opensearch-build/issues/4272 
For more information on following Developer Certificate of Origin and signing off your commits, please check …

update MAC agent node AMI ID

---

packer/scripts/macos/macos-agentsetup.sh

Adding a jenv package to setup $JAVA_HOME properly in Mac agent
part of https://github.com/opensearch-project/opensearch-build/issues/4272

Adding a jenv package to setup JAVA_HOME properly 

---

packer/scripts/macos/macos-agentsetup.sh

We are going to use update-alternatives from dpkg to set Java version on Mac agent node
https://github.com/opensearch-project/opensearch-build/issues/4272

Using update-alternatives from dpkg to set Java version on Mac agent node

---

README.md
lib/compute/agent-node-config.ts
package-lock.json
package.json
test/ci-stack.test.ts
test/data/test_env.yaml

Replace cdk-ec2-key-pair with CfnKeyPair construct to generate ec2 key pair. 
`aws-cdk-lib` provides `CfnKeyPair` construct to generate ec2 key-pairs. The private key is saved to AWS Systems Manager Parameter Store, using a parameter with the following name: /ec2/keypair/{key_pair_id}. See https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ec2.CfnKeyPair.html for more details. 

Replace cdk-ec2-key-pair with CfnKeyPair construct to generate ec2 key pair

---

lib/compute/jenkins-main-node.ts

using repo commit Id instead of contributor's
https://github.com/jenkinsci-cert/SECURITY-3314-3315/commit/55c15104fb70d6a2b46fd3f8ba7dec3913a4b1db
https://github.com/opensearch-project/opensearch-ci/issues/386

Jenkins CLI CVE - using repo commit Id instead of contributors

---

lib/monitoring/ci-alarms.ts

Switch Main Node CPU threshold from 50 to 75
Closes https://github.com/opensearch-project/opensearch-ci/issues/398

Switch Main Node CPU threshold from 50 to 75

---

.gitignore
lib/ci-stack.ts
lib/network/ci-external-load-balancer.ts
test/ci-stack.test.ts
test/compute/agent-node-config.test.ts

Adding one more layer of monitoring for security purpose by enabling access logging on load balancer. The logs will be written to the audit bucket within `loadBalancerAccessLogs` folder

Enable access logging for load balancer

---

lib/compute/jenkins-main-node.ts

Adding X-Forwarded-For header in httpd access_log
Ref: https://repost.aws/knowledge-center/elb-capture-client-ip-addresses
We want to enable the original source IP to be shown in httpd access_log.
The updated LogFormat can be added in the default` httpd.conf `or any configiuration that will be taken by the httpd.
In our case, the `jenkins.conf`.
Also, we only need to add customed `combined` LogFormat because the it is the enabled log format used in default httpd.conf.
here is the snippet of default httpd.conf where defines which log format is applied to access_log
```
#
#
#CustomLog "logs/access_log" common
#
#
CustomLog "logs/access_log" combined
</IfModule>
```
sample output in access_log after the implementation:
```
2.21.198.66 10.0.19.198 - - [20/Mar/2024:05:16:31 +0000] "GET / …
```

Adding X-Forwarded-For header in httpd access_log

---

lib/network/ci-external-load-balancer.ts
test/ci-stack.test.ts

The inline bucket policy cannot be recreated or added. It can only be modified as per documentation. Since users might have already existing bucket, this change prevents from breaking  

Add to existing policy instead of creating new one

---

lib/ci-stack.ts
lib/security/waf.ts
test/ci-stack.test.ts

Adding one more layer of security by adding WAF rules and associating with the load balancer. This prevents DDoS attack when endpoint is public.

Add WAF rules to protect Jenkins endpoint

---

packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh

Replace default curl 7.68 on Ubuntu 20.04 with 7.75+ version to support aws-sigv4
opensearch-project/opensearch-build#4469

Replace default curl 7.68 on Ubuntu 20.04 with 7.75+ version to support aws-sigv4

---

lib/compute/agent-nodes.ts

Replace ubuntu ami with updated curl from #406 #407
https://github.com/opensearch-project/opensearch-build/issues/4469

Replace ubuntu ami with updated curl from #406 #407

---

packer/jenkins-agent-win2019-x64.json
packer/scripts/windows/winrm_max_memory.ps1

Replace c54xlarge with m54xlarge for Windows Docker Host
https://github.com/opensearch-project/opensearch-ci/issues/412

Replace c54xlarge with m54xlarge for Windows Docker Host

---

.github/workflows/docker.yml
docker/Dockerfile

Upgrade Jenkins core image to 2.440.2 JDK21
https://github.com/opensearch-project/opensearch-ci/issues/389 

Upgrade Jenkins core image to 2.440.2 JDK21

---

lib/compute/agent-nodes.ts

After updating the `aws-cdk-lib` version to latest, `cdk deploy` command on benchmark host is failing with incompatible version error. the `aws-cdk` utility on benchmark host had to be updated to the latest version as well to resolve this issue. 

Updated benchmark agent ami-id

---

bin/ci-stack.ts
lib/buildArtifacts/artifacts-public-access.ts
lib/compute/agent-nodes.ts
lib/compute/jenkins-main-node.ts
lib/compute/run-additional-commands.ts
lib/monitoring/ci-alarms.ts
package-lock.json
package.json
resources/cf-url-rewriter/cf-url-rewriter.ts
test/ci-stack.test.ts

This PR: 
* Upgrades `aws-cdk-lib` library version to latest 2.134.0 version. 
* Replaces deprecated methods with ones supported by latest version. 
* Upgrades Main and agent node from AL2 to AL2023. 
#396 

Upgrade aws-cdk-lib to latest 2.134.0 version

---

.github/workflows/docker.yml
docker/Dockerfile

Change Jenkins core image to 2.426.3 JDK21

Change jenkins image to 2.426.3 JDK21

---

docker/plugins.txt

Set durable-task plugin to 547.vd1ea_007d100c

Set durable-task plugin to desired version

---

packer/jenkins-agent-al2-arm64.json
packer/jenkins-agent-al2-x64.json
packer/jenkins-agent-al2023-arm64.json
packer/jenkins-agent-al2023-x64.json
packer/jenkins-agent-macos12-x64.json
packer/jenkins-agent-ubuntu2004-x64.json
packer/jenkins-agent-win2019-x64-gradle-check.json
packer/jenkins-agent-win2019-x64.json
packer/scripts/al2/al2-agent-setups.sh
packer/scripts/al2023/al2023-agent-setups.sh
packer/scripts/macos/macos-agentsetup.sh
packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
packer/scripts/windows/legacy/scoop-install-commons.ps1
packer/scripts/windows/scoop-install-commons-docker-support.ps1

Creating new AMIs with default JDK21 on each agent
N/A

[Upgrade] Creating new AMIs with default JDK21

---

packer/jenkins-agent-al2-arm64.json
packer/jenkins-agent-al2-x64.json
packer/jenkins-agent-al2023-arm64.json
packer/jenkins-agent-al2023-x64.json
packer/jenkins-agent-macos12-x64.json
packer/jenkins-agent-ubuntu2004-x64.json
packer/jenkins-agent-win2019-x64-gradle-check.json
packer/jenkins-agent-win2019-x64.json
packer/scripts/al2/al2-agent-setups.sh
packer/scripts/al2023/al2023-agent-setups.sh
packer/scripts/macos/macos-agentsetup.sh
packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
packer/scripts/windows/legacy/scoop-install-commons.ps1
packer/scripts/windows/scoop-install-commons-docker-support.ps1

Setting JDK21 as default Java version on Jenkins agents
https://github.com/opensearch-project/opensearch-ci/issues/389 

[Upgrade] Setting JDK21 as default Java version on Jenkins agents

---

lib/compute/oidc-config.ts

- Update deprecated assignments to entries 
- Fix failing role-strategy-plugin
Add syntax changes for jenkins.yaml file from
assignments:
- admin
to-
entries:
- user: admin
https://github.com/opensearch-project/opensearch-ci/issues/389
Related documentation
https://issues.jenkins.io/browse/JENKINS-71612

Update deprecated assignments to entries 

---

lib/compute/jenkins-main-node.ts
lib/compute/oidc-config.ts
test/compute/jenkins-main-node.test.ts
test/data/test_env.yaml

`cronie` package that provides `crontab` functionality has been deprecated in AL2023 and the work around is to install it manually. Discussion is still on whether to include or not to include in future amis. https://github.com/amazonlinux/amazon-linux-2023/issues/300. 

Install cronie package on main node

---

lib/compute/jenkins-main-node.ts

Add cloudwatch logs for gradle-check job. 
In the future similar configuration can be added if we want to onboard other job logs as well. 

Add cloudwatch logs for gradle-check job

---

packer/jenkins-agent-al2-arm64.json
packer/jenkins-agent-al2-x64.json
packer/jenkins-agent-al2023-arm64.json
packer/jenkins-agent-al2023-x64.json
packer/jenkins-agent-macos12-x64.json
packer/jenkins-agent-ubuntu2004-x64.json
packer/jenkins-agent-win2019-x64-gradle-check.json
packer/jenkins-agent-win2019-x64.json

Ensure packer to provision EC2 instance with imdsv2 enabled
Note that this will not make the AMI itself to be imdsv2 only
We currently still maintain the ability for AMI to be both imdsv1 and imdsv2, and use Jenkins EC2 plugin to enforce the imdsv2 during provision of agents.
Thanks.
https://github.com/opensearch-project/opensearch-ci/issues/435

Ensure packer to provision EC2 instance with imdsv2 enabled

---

packer/scripts/al2/al2-agent-setups.sh
packer/scripts/al2023/al2023-agent-setups.sh
packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh

Install pigz and unpigz to speed up docker image extraction
Closes https://github.com/opensearch-project/opensearch-ci/issues/374

Install pigz and unpigz to speed up docker image extraction

---

package-lock.json
package.json

Bump both micromatch to ^4.0.6 and braces to 3.0.3 accordingly
https://github.com/opensearch-project/opensearch-ci/pull/441

Bump both micromatch to ^4.0.6 and braces to 3.0.3 accordingly

---

lib/compute/agent-nodes.ts

Fix macos arm64 agent label name
https://github.com/opensearch-project/opensearch-build/issues/4670

Fix macos arm64 agent label name

---

lib/compute/agent-nodes.ts

Make sure Ubuntu is using JDK21 when connecting to Main node
```
Jul 23, 2024 12:04:05 AM hudson.plugins.ec2.EC2Cloud
INFO: Creating ~/.hudson-run-init
Jul 23, 2024 12:04:05 AM hudson.plugins.ec2.EC2Cloud
INFO: Verifying: java -fullversion
openjdk full version "11.0.22+7"
Jul 23, 2024 12:04:08 AM hudson.plugins.ec2.EC2Cloud
INFO: Verifying: which scp
/usr/bin/scp
Jul 23, 2024 12:04:08 AM hudson.plugins.ec2.EC2Cloud
INFO: Copying remoting.jar to: /tmp
Jul 23, 2024 12:04:08 AM hudson.plugins.ec2.EC2Cloud
INFO: Launching remoting agent (via Trilead SSH2 Connection):  java  -jar /tmp/remoting.jar -workDir /var/jenkins
<===[JENKINS REMOTING CAPACITY]===>Remoting version: 3160.vd76b_9ddd10cc
Launcher: EC2UnixLauncher
Communication Protocol: Standard in/out
This is a Unix agent
Evacuated stdout …
```

Make sure Ubuntu is using JDK21 when connecting to Main node

---

lib/compute/jenkins-main-node.ts

Disable auto log file removal for Jenkins gradle check logs
https://github.com/opensearch-project/opensearch-ci/issues/484

Disable auto log file removal for Jenkins gradle check logs

---

lib/compute/agent-node-config.ts
packer/scripts/macos/macos-agentsetup.sh
packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh

Support JDK-23 builds on CI agents
Part of https://github.com/opensearch-project/OpenSearch/issues/16255

Support JDK-23 builds on CI agents

---

lib/compute/agent-nodes.ts

Update spare instance number on al2023 docker host
old: 3 spare * 4 executors = 12 waiting
new: 4 spare * 3 executors = 12 waiting.
That is because the old name for M5 M6g is DOCKER_HOST_EXTRA which is only used for integ.
There used to be DOCKER_HOST with 3 spare, and DOCKER_HOST_EXTRA with 1 spare.
Now I remove old DOCKER_HOST and rename EXTRA to the same name.
Therefore the new DOCKER_HOST needs to have 4 spare instances.
Thanks.
https://github.com/opensearch-project/opensearch-build/issues/5082
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRI …

Update spare instance number on al2023 docker host

---

lib/compute/agent-node-config.ts

Update windows boot delay from 7.5 seconds to 180 seconds
```
Indicate here the time in seconds to wait for the machine to be ready once the plugin detects WinRM is available.
...
A safe value has been found to be 3 minutes. 
```
```
WinRM service responded. Waiting 180000ms for WinRM service to stabilize on EC2 (Amazon_ec2_cloud) - jenkinsAgentNode-Jenkins-Agent-Windows2019-X64-M54xlarge-Docker-Builder (<>)
```
opensearch-project/opensearch-build#5004

Update windows boot delay from 7.5 seconds to 180 seconds

---

packer/scripts/macos/macos-agentsetup.sh

Replace py39-python-installer with python39 due to port removal
https://github.com/opensearch-project/opensearch-build/issues/5096#issuecomment-2465866042

Replace py39-python-installer with python39 due to port removal

---

.github/workflows/docker.yml
docker/plugins.txt

This change installs github-oauth plugin version: `597.ve0c3480fcb_d0 `
This change **DOES NOT** enable GitHub Auth yet.
Also adds conditional check to the docker workflow to only execute for this repo.
related https://github.com/opensearch-project/opensearch-ci/issues/506

Install github-oauth plugin

---

lib/ci-config-stack.ts
lib/ci-stack.ts

While updating the currently deployed stack, removing the old value is causing issues as ci-stack is dependent on it. Hence, the current stack won't delete the oidc secret. This change keeps the value as is along with new auth values

Restore previous secrets and update cfn parameter

---

.gitignore
README.md
configHelper/.coveragerc
configHelper/Pipfile
configHelper/Pipfile.lock
configHelper/README.md
configHelper/configHelper/config_helper.py
configHelper/tests/resources/sampleJenkinsGithubAuth.yaml
configHelper/tests/resources/sampleJenkinsNoSecurityRealm.yaml
configHelper/tests/resources/sampleJenkinsOICAuth.yaml
configHelper/tests/test_config_helper.py
lib/compute/auth-config.ts
lib/compute/jenkins-main-node.ts
test/compute/auth-config.test.ts
test/compute/jenkins-main-node.test.ts

This feature adds a `configHelper` python utility script to make modifying the Jenkins CASC yaml easier to understand and test locally. This script replaces previous shell functionality to add authConfig into the `jenkins.yaml` and extends support to allow nested secret structures to be placed in the authConfig secret which unblocks the current OIC auth pattern which has had a breaking change that requires this nested structure.
https://github.com/opensearch-project/opensearch-ci/issues/515
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.m …

Add config helper utility to improve modifying Jenkins CASC yaml

---

packer/scripts/windows/scoop-install-commons-docker-support.ps1

Update windows https transport to use openssl
https://github.com/opensearch-project/opensearch-ci/issues/523

Update windows https transport to use openssl

---

lib/compute/jenkins-main-node.ts

Adds missing echo keyword which is failing the resource creation when authType is set to default.

Fix configHelper bug for authTpye default

---

packer/scripts/ubuntu/ubuntu2404-agent-setups.sh

Update ci ubuntu2404 script on awscliv2 installation
https://github.com/opensearch-project/opensearch-build/issues/5270
https://github.com/opensearch-project/opensearch-build/issues/3747

Update ci ubuntu2404 script on awscliv2 installation

---

lib/compute/agent-nodes.ts
packer/scripts/ubuntu/ubuntu2404-agent-setups.sh
test/ci-stack.test.ts

Resolve ubuntu2404 agents startup issues on EC2 
https://github.com/opensearch-project/opensearch-build/issues/5270
https://github.com/opensearch-project/opensearch-build/issues/3747

Resolve ubuntu2404 agents startup issues on EC2 

---

lib/compute/jenkins-main-node.ts

localhost:8080/api/json?pretty needs auth to be passed to check the availability. Instead using localhost:8080/login that does not require auth and correctly detects jenkins check for http status codes

Update jenkins availability URL to non-auth one

---

lib/compute/agent-nodes.ts

Exclude openssl updates to prevent broken AL2023 bootstrap.
Python* is removed as it is not broken anymore.
Thanks.
Closes https://github.com/opensearch-project/opensearch-ci/issues/544

Exclude openssl updates to prevent broken AL2023 bootstrap

---

lib/ci-stack.ts
lib/compute/jenkins-main-node.ts
test/ci-stack.test.ts

- In order to enhance the security, we want to monitor the httpd access logs as well. This change adds a new log group and stream reading the httpd access log file.
- Also switches VPCflowLogs from S3 to cloudwatch 
closes https://github.com/opensearch-project/opensearch-ci/issues/538

Refactor vpc flow logs logging and monitor httpd access logs

---

lib/compute/agent-nodes.ts

Add missing openssl exclusion for AL2023 X64 Single Host
A followup: https://github.com/opensearch-project/opensearch-ci/pull/545

Add missing openssl exclusion for AL2023 X64 Single Host

---

lib/compute/agent-node-config.ts
packer/scripts/macos/macos-agentsetup.sh
packer/scripts/ubuntu/ubuntu2404-agent-setups.sh
resources/baseJenkins.yaml

Update runners to update with jdk 24 now
https://github.com/opensearch-project/opensearch-build/pull/5426

Update runners to update with jdk 24 now

---

bin/ci-stack.ts
bin/stage-definitions.ts
lib/compute/jenkins-main-node.ts
lib/monitoring/ci-alarms.ts
resources/envVars.yaml

This is just a consolidated PR over @Divyaasm work to move jenkins ci stack deployment to opensource model. 
I have a made a few changes, such as:
* Make `stage` context var mandatory for user to specify which stack to deploy. will make it easy to specify in github actions workflow. 
* Added a hack to not delete certain exports that are used by amazon internal monitoring system, will be removed when we move to slack notification or any other opensource system. 
For more information on following Developer Certificate of Origin and signing off your commits, please check …

Changes to move ci stack deployment to github action. 

---

packer/scripts/al2/al2-agent-setups.sh

Update al2 scripts to support AMI in 2025
`amazon-ebs.Jenkins-Agent-AL2-X64-2025-05-30T07-28-10Z: ERROR: This script does not work on Python 3.7. The minimum supported Python version is 3.9. Please use https://bootstrap.pypa.io/pip/3.7/get-pip.py instead.`

Update al2 scripts to support AMI in 2025

---

lib/compute/agent-nodes.ts

Update latest AL2 AMI and disable Windows Single Host
```
java.io.IOException: Remote call on EC2 (Amazon_ec2_cloud) - jenkinsAgentNode-Jenkins-Agent-Windows2019-X64-C524xlarge-Single-Host (i-<>) failed
```

Update latest AL2 AMI and disable Windows Single Host

---

lib/ci-stack.ts
test/compute/agent-node-config.test.ts

Add flexibility for other users of this stack to specific their own agent configuration.
- Resolves https://github.com/opensearch-project/opensearch-ci/issues/405

Allow for agent node configuration to be manually supplied

---

lib/ci-stack.ts
lib/secrets/gha-federate-access.ts
lib/secrets/secret-credentials.ts
package-lock.json
test/ci-stack.test.ts
test/compute/agent-node-config.test.ts

This PR moves the secrets creation logic to public ci-stack. The logic is such that it should not delete the existing secrets created using internal stack and only introduce new secrets.

move secrets logic to public stack

---

lib/compute/agent-nodes.ts

Switch windows AMI to 202502 version to temp resolve 202506 image startup issues
https://github.com/opensearch-project/opensearch-build/issues/5535

Switch windows AMI to 202502 version to temp resolve 202506 image startup issues

---

lib/secrets/secret-credentials.ts
test/ci-stack.test.ts

We are planning on retrieving data prepper artifacts using s3Download for which we would need role name and account ID of the data-prepper S3 bucket where artifacts are hosted. Adding them as secrets so that it can be used in code using `withCredentials` block.
Also refactors some of the code where secrets were static which are not required. 
part of https://github.com/opensearch-project/opensearch-build/issues/5586

Add data prepper account details as credentials

---

lib/secrets/secret-credentials.ts
package-lock.json
package.json

- This minor change updates the maven credentials with right name and description.
- Also removes repo access to these credentials as we are now using one password via LF instead of AWS secrets.
- We were also not bumping the package.json which should match the tag version everytime. Fixing it too.
https://github.com/opensearch-project/opensearch-build/issues/5551 https://github.com/opensearch-project/opensearch-build/issues/5548

Update maven secrets and remove repo access

---

lib/compute/jenkins-main-node.ts
package-lock.json
package.json

Cloudwatch agent was being killed due to below error:
```
2025-07-02T17:12:11Z I! [logagent] piping log from JenkinsMainNode/gradle-check.log/gradle-check.log/2025-07-01(/var/lib/jenkins/jobs/gradle-check/builds/59946/log) to cloudwatchlogs with retention -1
2025-07-02T17:18:55Z E! [inputs.logfile] Failed to find target files for file config /var/lib/jenkins/jobs/gradle-check/builds/*/log, with error: error tailing file /var/lib/jenkins/jobs/gradle-check/builds/55494/log with error: lstat /var/lib/jenkins/jobs/gradle-check/builds/55494
: no such file or directory
```
The log discarder is set to [90 days](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/gradle/gradle-check.jenkinsfile#L19) which causes the older files to be missing. Removing the log monitoring for …

Remove gradle check logger to fix cloudwatch agent failures

---

lib/compute/jenkins-main-node.ts
package-lock.json
package.json

Set auto removal to false for workflow run logs as cloudwatch agent is deleting the file after reading causing the logger to stop writing. 

Set auto removal to false for workflow run logs

---

bin/ci-stack.ts

Add OSCAR chatbot related build access role through opensearch-ci-bot
https://github.com/opensearch-project/opensearch-build/issues/5684

Add OSCAR chatbot related build access role through opensearch-ci-bot
